web:
  image: "nginx:latest"
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/key.pem:/etc/nginx/key.pem:ro
    - ./nginx/cert.pem:/etc/nginx/cert.pem:ro